const {
  calculateRecoveryScore,
} = require("./recoveryService");

const {
  analyzePaymentWithAI,
} = require("./aiService");

const {
  evaluateRecoveryPolicy,
} = require("./policyService");

// =========================================================
// CONTROLLED BENCHMARK DEFINITIONS
// =========================================================
//
// IMPORTANT:
// These are ground-truth labels for the synthetic benchmark.
// They are NOT generated by the AI.
//
// The benchmark measures:
// 1. AI decision agreement with scenario ground truth
// 2. Policy safety
// 3. Eligible recovery
// 4. Simulated recovery outcome
// =========================================================

const SCENARIOS = {
  high_recovery: {
    amount: 500,
    method: "upi",
    retryCount: 0,
    successfulHistory: 6,
    failedHistory: 1,
    failureCode: "TEMPORARY_FAILURE",

    expectedAction: "RETRY",

    // If RETRY is authorized, this synthetic payment succeeds.
    expectedOutcome: "SUCCESS",
  },

  weak_customer: {
    amount: 500,
    method: "netbanking",
    retryCount: 0,
    successfulHistory: 0,
    failedHistory: 1,
    failureCode: "BAD_REQUEST_ERROR",

    expectedAction: "REVIEW",

    // REVIEW is intentionally not an automatic recovery.
    expectedOutcome: "FAILURE",
  },

  high_risk: {
    amount: 75000,
    method: "card",
    retryCount: 3,
    successfulHistory: 1,
    failedHistory: 5,
    failureCode: "REPEATED_FAILURE",

    expectedAction: "STOP",

    expectedOutcome: "FAILURE",
  },

  medium_recovery: {
    amount: 2500,
    method: "card",
    retryCount: 1,
    successfulHistory: 3,
    failedHistory: 1,
    failureCode: "TEMPORARY_FAILURE",

    expectedAction: "REVIEW",

    // REVIEW means no automatic execution.
    expectedOutcome: "SUCCESS",
  },
};

// =========================================================
// BUILD CUSTOMER STATS
// =========================================================

const buildCustomerStats = ({
  index,
  successfulHistory,
  failedHistory,
}) => {
  const totalTransactions =
    successfulHistory +
    failedHistory +
    1;

  const failedPayments =
    failedHistory + 1;

  const failureRate =
    totalTransactions > 0
      ? Number(
          (
            (failedPayments /
              totalTransactions) *
            100
          ).toFixed(2)
        )
      : 0;

  return {
    email:
      `synthetic_${index}@revenuex.test`,

    totalTransactions,

    successfulPayments:
      successfulHistory,

    failedPayments,

    totalSuccessfulRevenue:
      successfulHistory * 1000,

    failureRate,
  };
};

// =========================================================
// BUILD SYNTHETIC TRANSACTION
// =========================================================

const buildTransaction = ({
  index,
  scenario,
  config,
}) => ({
  _id:
    `experiment_${scenario}_${index}`,

  amount:
    config.amount,

  currency: "INR",

  status: "failed",

  method:
    config.method,

  failureReason:
    "payment_failed",

  failureCode:
    config.failureCode,

  retryCount:
    config.retryCount,

  simulation: true,

  recoveryStatus:
    "NOT_ATTEMPTED",

  recoveredAmount: 0,
});

// =========================================================
// RUN BATCH EXPERIMENT
// =========================================================

const runBatchExperiment = async ({
  count = 100,
}) => {
  // ---------------------------------------------------------
  // SANITIZE COUNT
  // ---------------------------------------------------------

  const requestedCount =
    Number(count);

  const totalCases =
    Number.isFinite(requestedCount) &&
    requestedCount > 0
      ? Math.min(
          Math.floor(requestedCount),
          1000
        )
      : 100;

      const results = [];

  // ---------------------------------------------------------
  // METRICS
  // ---------------------------------------------------------

  let totalAtRisk = 0;
  let eligibleRevenue = 0;
  let totalRecovered = 0;

  let recoveryAttempts = 0;
  let blockedActions = 0;
  let escalatedActions = 0;
  let stoppedActions = 0;

  let successfulRecoveries = 0;
  let failedRecoveries = 0;

  let policyViolations = 0;

  let correctDecisions = 0;
  let incorrectDecisions = 0;

  // ---------------------------------------------------------
  // ACTION SUMMARY
  // ---------------------------------------------------------

  const actionSummary = {
    RETRY: 0,
    REVIEW: 0,
    STOP: 0,
  };

  const expectedActionSummary = {
    RETRY: 0,
    REVIEW: 0,
    STOP: 0,
  };

  // ---------------------------------------------------------
  // POLICY SUMMARY
  // ---------------------------------------------------------

  const policySummary = {
    ALLOW: 0,
    BLOCK: 0,
  };

  // ---------------------------------------------------------
  // SCENARIO SUMMARY
  // ---------------------------------------------------------

  const scenarioSummary = {};

  Object.entries(SCENARIOS).forEach(
    ([name, config]) => {
      scenarioSummary[name] = {
        cases: 0,

        expectedAction:
          config.expectedAction,

        expectedOutcome:
          config.expectedOutcome,

        allowed: 0,
        blocked: 0,

        recovered: 0,
        failed: 0,

        correctDecisions: 0,
        incorrectDecisions: 0,

        recoveredAmount: 0,
      };
    }
  );

  // =========================================================
  // DETERMINISTIC DISTRIBUTION
  // =========================================================

  const highRecoveryCount =
    Math.round(
      totalCases * 0.35
    );

  const weakCustomerCount =
    Math.round(
      totalCases * 0.35
    );

  const highRiskCount =
    Math.round(
      totalCases * 0.20
    );

  const mediumRecoveryCount =
    totalCases -
    highRecoveryCount -
    weakCustomerCount -
    highRiskCount;

  const scenarios = [];

  for (
    let i = 0;
    i < highRecoveryCount;
    i++
  ) {
    scenarios.push(
      "high_recovery"
    );
  }

  for (
    let i = 0;
    i < weakCustomerCount;
    i++
  ) {
    scenarios.push(
      "weak_customer"
    );
  }

  for (
    let i = 0;
    i < highRiskCount;
    i++
  ) {
    scenarios.push(
      "high_risk"
    );
  }

  for (
    let i = 0;
    i < mediumRecoveryCount;
    i++
  ) {
    scenarios.push(
      "medium_recovery"
    );
  }

  // =========================================================
  // PROCESS CASES
  // =========================================================

  for (
    let i = 0;
    i < totalCases;
    i++
  ) {
    const scenario =
      scenarios[i];

    const config =
      SCENARIOS[scenario];

    const expectedAction =
      config.expectedAction;

    const expectedOutcome =
      config.expectedOutcome;

    const summary =
      scenarioSummary[scenario];

    summary.cases++;

    expectedActionSummary[
      expectedAction
    ]++;

    // -------------------------------------------------------
    // TRANSACTION
    // -------------------------------------------------------

    const transaction =
      buildTransaction({
        index: i,
        scenario,
        config,
      });

    totalAtRisk +=
      transaction.amount;

    // -------------------------------------------------------
    // CUSTOMER CONTEXT
    // -------------------------------------------------------

    const customerStats =
      buildCustomerStats({
        index: i,
        successfulHistory:
          config.successfulHistory,
        failedHistory:
          config.failedHistory,
      });

    // -------------------------------------------------------
    // RECOVERY SCORE
    // -------------------------------------------------------

    const recovery =
      calculateRecoveryScore(
        transaction,
        customerStats
      );

    // -------------------------------------------------------
    // AI CONTEXT
    // -------------------------------------------------------

    const context = {
      payment: {
        amount:
          transaction.amount,

        currency:
          transaction.currency,

        method:
          transaction.method,

        failureReason:
          transaction.failureReason,

        failureCode:
          transaction.failureCode,

        retryCount:
          transaction.retryCount,
      },

      customer:
        customerStats,

      recovery: {
        score:
          recovery.score,

        riskLevel:
          recovery.riskLevel,

        deterministicRecommendation:
          recovery.recommendedAction,
      },
    };

    // -------------------------------------------------------
    // AI DECISION
    // -------------------------------------------------------

    const aiDecision =
      await analyzePaymentWithAI(
        context
      );

    const actualAction =
      aiDecision.recommendedAction;

    actionSummary[
      actualAction
    ] =
      (actionSummary[
        actualAction
      ] || 0) + 1;

    // -------------------------------------------------------
    // DECISION AGREEMENT
    // -------------------------------------------------------

    const decisionMatch =
      actualAction ===
      expectedAction;

    if (decisionMatch) {
      correctDecisions++;

      summary.correctDecisions++;
    } else {
      incorrectDecisions++;

      summary.incorrectDecisions++;
    }

    // -------------------------------------------------------
    // POLICY
    // -------------------------------------------------------

    const policy =
      evaluateRecoveryPolicy({
        transaction,
        aiDecision,
      });

    if (policy.allowed) {
      policySummary.ALLOW++;

      eligibleRevenue +=
        transaction.amount;

      recoveryAttempts++;

      summary.allowed++;
    } else {
      policySummary.BLOCK++;

      blockedActions++;

      summary.blocked++;

      if (
        actualAction ===
        "REVIEW"
      ) {
        escalatedActions++;
      }

      if (
        actualAction ===
        "STOP"
      ) {
        stoppedActions++;
      }

      if (
        Array.isArray(
          policy.violations
        ) &&
        policy.violations.length >
          0
      ) {
        policyViolations++;
      }
    }

    // =======================================================
    // SIMULATED EXECUTION
    // =======================================================
    //
    // IMPORTANT:
    // Only an ALLOWED action can execute.
    //
    // The benchmark does NOT call Razorpay.
    // It models the outcome of a bounded synthetic retry.
    // =======================================================

    let executionOutcome =
      "NOT_EXECUTED";

    let finalStatus =
      "BLOCKED";

    let recoveredAmount = 0;

    if (policy.allowed) {
      executionOutcome =
        expectedOutcome;

      if (
        executionOutcome ===
        "SUCCESS"
      ) {
        successfulRecoveries++;

        finalStatus =
          "RECOVERED";

        recoveredAmount =
          transaction.amount;

        totalRecovered +=
          transaction.amount;

        summary.recovered++;

        summary.recoveredAmount +=
          transaction.amount;
      } else {
        failedRecoveries++;

        finalStatus =
          "FAILED";

        summary.failed++;
      }
    }

    // -------------------------------------------------------
    // CASE RESULT
    // -------------------------------------------------------

    results.push({
      caseNumber:
        i + 1,

      scenario,

      amount:
        transaction.amount,

      // Ground truth
      expectedAction,
      expectedOutcome,

      // AI
      actualAction,

      aiAction:
        actualAction,

      aiConfidence:
        aiDecision.confidence,

      diagnosis:
        aiDecision.diagnosis,

      reason:
        aiDecision.reason,

      // Recovery intelligence
      recoveryScore:
        recovery.score,

      riskLevel:
        recovery.riskLevel,

      // Policy
      policyDecision:
        policy.decision,

      policyAllowed:
        policy.allowed,

      policyReason:
        policy.reason,

      policyViolations:
        policy.violations || [],

      // Outcome
      executionOutcome,

      finalStatus,

      recoveredAmount,

      // Benchmark
      decisionMatch,

      simulation: true,
    });
  }

  // =========================================================
  // FINAL METRICS
  // =========================================================

  const recoveryRate =
    totalAtRisk > 0
      ? Number(
          (
            (totalRecovered /
              totalAtRisk) *
            100
          ).toFixed(2)
        )
      : 0;

  const eligibleRecoveryRate =
    eligibleRevenue > 0
      ? Number(
          (
            (totalRecovered /
              eligibleRevenue) *
            100
          ).toFixed(2)
        )
      : 0;

  const blockedRate =
    totalCases > 0
      ? Number(
          (
            (blockedActions /
              totalCases) *
            100
          ).toFixed(2)
        )
      : 0;

  const decisionAgreement =
    totalCases > 0
      ? Number(
          (
            (correctDecisions /
              totalCases) *
            100
          ).toFixed(2)
        )
      : 0;

  const policySafetyRate =
    totalCases > 0
      ? Number(
          (
            ((totalCases -
              policyViolations) /
              totalCases) *
            100
          ).toFixed(2)
        )
      : 100;

  // =========================================================
  // RETURN BENCHMARK
  // =========================================================

  return {
    totalCases,

    benchmarkType:
      "CONTROLLED_SYNTHETIC",

    note:
      "Ground-truth actions and outcomes are predefined scenario labels. Recovery results are simulated and do not represent live payment recovery.",

    totalAtRisk,

    eligibleRevenue,

    totalRecovered,

    recoveryRate,

    eligibleRecoveryRate,

    recoveryAttempts,

    successfulRecoveries,

    failedRecoveries,

    blockedActions,

    blockedRate,

    escalatedActions,

    stoppedActions,

    policyViolations,

    policySafetyRate,

    correctDecisions,

    incorrectDecisions,

    decisionAgreement,

    expectedActionSummary,

    actionSummary,

    policySummary,

    scenarioSummary,

    results,
  };
};

module.exports = {
  runBatchExperiment,
};